name: boosty MERN CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    # job tasks to run
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install backend dependencies and run test
        run: |
          cd backend
          npm ci
          npm run 

      - name: Install frontend dependences and build
        run: |
          cd frontend
          npm ci
          npm run build
      - name: Install backend dependencies and run tests
        run: |
          cd backend
          npm ci
          npm run build

      - name: Install frontend dependences and build
        run: |
          cd frontend
          npm ci
          npm run build
